version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Docker image"
          command: |
            echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_LOGIN} --password-stdin
            if [ "${CIRCLE_TAG}" != "" ]; then
              docker build -t cevantime/cd_app:${CIRCLE_TAG} --build-arg DATABASE_URL=${DATABASE_URL} --build-arg APP_ENV=${APP_ENV} --build-arg APP_DEBUG=${APP_DEBUG} .
              docker tag cevantime/cd_app:${CIRCLE_TAG} cevantime/cd_app:latest
              docker push cevantime/cd_app:${CIRCLE_TAG}
            else
              docker build -t cevantime/cd_app --build-arg DATABASE_URL=${DATABASE_URL} --build-arg APP_ENV=${APP_ENV} --build-arg APP_DEBUG=${APP_DEBUG} .
              docker push cevantime/cd_app
            fi
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d6:ba:09:c8:ab:84:fa:f1:21:53:02:82:6e:06:59:96"
      - run:
          name: "Deploy image on kube cluster"
          command: |
            ssh root@${PRODUCTION_SERVER_IP} "cd ${PRODUCTION_SERVER_PATH} && ./deploy ${CIRCLE_TAG}"

workflows:
  version: 2.1
  staging:
    when:
      and:
        - equal: [master, << pipeline.git.branch >>]
    jobs:
      - build:
          context:
            - staging
  prod:
    when: << pipeline.git.tag >>
    jobs:
      - build:
          context:
            - production
          filters:
            tags:
              only: /v.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v.*/
